# Generated by Django 5.1.3 on 2024-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reaction_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
